import "@/styles/globals.css";

import { Outfit } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${outfit.variable} font-medium antialiased text-lg bg-wash dark:bg-wash-dark text-secondary dark:text-secondary-dark leading-base`}>
        <script
          dangerouslySetInnerHTML={{
            __html: `
            (function () {
              function setTheme(newTheme) {
                window.__theme = newTheme;
                if (newTheme === 'dark') {
                  document.documentElement.classList.add('dark');
                }
                document.documentElement.classList.remove('dark');
              }

              let theme;
              try {
                theme = localStorage.getItem('theme');
              } catch (err) { }

              window.__setTheme = function(newTheme) {
                theme = newTheme;
                setTheme(newTheme);
                try {
                  localStorage.setItem('theme', newTheme);
                } catch (err) { }
              };

              let initialTheme = theme;
              const themeQuery = window.matchMedia('(prefers-color-scheme: dark)');

              if (!initialTheme) {
                initialTheme = themeQuery.matches ? 'dark' : 'light';
              }
              setTheme(initialTheme);

              themeQuery.addEventListener('change', function (e) {
                if (!theme) {
                  setTheme(e.matches ? 'dark' : 'light');
                }
              });
            })();
            `
          }}
        />
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
